name: DataUpdate
on:
  schedule:
    - cron: '0 13 * * 1'

  # Enable running workflow from actions tab
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}

      - name: Setup Bun Runtime
        uses: antongolub/action-setup-bun@v1

      - name: Install Dependencies
        run: bun install

      - name: Log files
        run: ls -lh

      - name: Update conflicts
        run: bun run generate:conflicts

      - name: Update countries
        run: bun run generate:countries

      - name: Git Commit
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: Update countries.gen.json
